version: '3.9'

services:
  api:
    build: ./api
    container_name: real-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - HOST=http://real-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: real-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - HOST=http://real-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    image: mongo:latest
    container_name: real-docker-api-db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: real-docker-auth-db
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth:
